sixfeetup/scaf-fullstack-template

{{copier__project_slug}}/.github/dependabot.yml

Ticket: [#410](https://github.com/sixfeetup/scaf/issues/410)
Scaf doesn't support dependabot
Ensure all new projects in scaf include Dependabot configuration by adding it to the scaffolding setup.
<details>
| …

feat: configure dependabot #410

---

{{copier__project_slug}}/k8s/_monitoring/loki-stack-values.yaml
{{copier__project_slug}}/k8s/base/celery.yaml
{{copier__project_slug}}/k8s/base/django.yaml
{{copier__project_slug}}/k8s/base/flower.yaml
{{copier__project_slug}}/k8s/base/frontend.yaml
{{copier__project_slug}}/k8s/base/kustomization.yaml
{{copier__project_slug}}/k8s/base/pod-disruption-budgets.yaml
{{copier__project_slug}}/k8s/base/pod-priority.yaml
{{copier__project_slug}}/k8s/base/redis.yaml
{{copier__project_slug}}/k8s/local/postgres.yaml
{{copier__project_slug}}/k8s/sandbox/postgres.cnpg.yaml

Ticket: [#457](https://github.com/sixfeetup/scaf/issues/457)
Pod priority classes and PodDisruptionBudgets for the services were missing.
Implemented Pod priority classes and PodDisruptionBudgets for the services, ensuring that high-priority workloads are protected against evictions and disruptions.
<details>
| :monocle_face: **Code clarity** | Is the code easy to understand? Are variable and function names …

feat: Add pod priority class and pod disruption budgets #457

---

{{copier__project_slug}}/.github/workflows/semantic-release.yaml

Ticket: [#430](https://github.com/sixfeetup/scaf/issues/430)
Project creation was failing because of secrets configuration
Reformatted the secrets configuration values
<details>
| :carpentry_saw: …

fix: update secrets

---

copier.yml
nextjs-django-github.test-data.yml
tasks.py

Ticket: [#12](https://github.com/sixfeetup/scaf-fullstack-template/issues/12)
Remove the debug options from the copier template

feat: remove debug from scaf options

---

copier.yml

Ticket: https://github.com/sixfeetup/scaf-fullstack-template/issues/17

feat: calculate default value for project dash

---

copier.yml
nextjs-django-github.test-data.yml

Ticket: https://github.com/sixfeetup/scaf-fullstack-template/issues/18

feat: adjust defautl setting for mail

---

{{copier__project_slug}}/backend/config/schema.py
{{copier__project_slug}}/backend/config/settings/base.py
{{copier__project_slug}}/backend/config/settings/local.py
{{copier__project_slug}}/backend/{{copier__project_slug}}/users/tests/test_graphql_views.py
{{copier__project_slug}}/backend/{{copier__project_slug}}/users/tests/test_views.py
{{copier__project_slug}}/backend/{{copier__project_slug}}/users/urls.py
{{copier__project_slug}}/backend/{{copier__project_slug}}/utils/debugger.py

Ticket: [#127](https://github.com/sixfeetup/scaf/issues/127)
Lint and formatting checks were failing
Fixed lint issue
<details>
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or …

fix: lint issues #127

---

tasks.py
{{copier__project_slug}}/backend/config/settings/base.py

Ticket: #480
AWS Lambda app template should successfully run through scaf [#480](https://github.com/sixfeetup/scaf/issues/480)
Template setup for the project was initially done in scaf for all templates
Move Project initial setup from scaf to template
<details>
| :jigsaw: **Code organization** | Are …

feat: Move project setup from scaf to copier tasks

---

{{copier__project_slug}}/docs/architecture.md
{{copier__project_slug}}/docs/dataflow.md
{{copier__project_slug}}/docs/project-overview.md

Ticket: resolves #44 
first pass at dataflow and architecture diagrams, as well as an overview.
<details>
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or redundant code?
| …

#44 Data Flow Diagram

---

{{copier__project_slug}}/terraform/github/oidc.tf

Ticket: #57
Terraform was failing due to a syntax issue with repeated closing braces.
Removed the brace.
<details>
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or redundant …

chore: fix syntax error in oidc terraform (#57)

---

{{copier__project_slug}}/.github/workflows/main.yaml

Ticket: #53
Credentials weren't being carried forward, needed to be added to the generated workflows
Updated to persist the credentials across the workflow
<details>
| :carpentry_saw: **Conciseness** | Is the …

chore: github persist credentials (#53)

---

{{copier__project_slug}}/backend/{{copier__project_slug}}/utils/__init__.py

Ticket: #51
Fix issue with linting
Added noqa to prevent linting errors
<details>
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or redundant code?
| :speech_balloon: **Comments …

chore: added noqa for correct debugger import in utils (#51)

---

{{copier__project_slug}}/backend/Dockerfile

Ticket: #72 
Dockerfile env were not standardized
Dockerfile ENV values should have an equals
<details>
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or redundant code?
| …

feat: Update docker env values to have an equals #72

---

{{copier__project_slug}}/.github/workflows/main.yaml

Ticket: #73 
(Also in the title)
Github action was not building and pushing frontend images.
Updated github actions to build and push frontend images if frontend is selected yes in questions
<details>
| …

feat: Update github action to build and push frontend images as well #73

---

{{copier__project_slug}}/Makefile
{{copier__project_slug}}/terraform/modules/base/ec2.tf
{{copier__project_slug}}/terraform/modules/base/variables.tf

The disk_size was not set correctly before.

fix: specify disk size

---

{{copier__project_slug}}/k8s/sandbox/kustomization.yaml

resolves https://github.com/sixfeetup/scaf/issues/509

fix: identation

---

{{copier__project_slug}}/.github/workflows/main.yaml
{{copier__project_slug}}/backend/config/settings/production.py
{{copier__project_slug}}/backend/config/urls.py
{{copier__project_slug}}/frontend/components/NavBar.tsx
{{copier__project_slug}}/frontend/pages/about.tsx
{{copier__project_slug}}/frontend/pages/index.tsx
{{copier__project_slug}}/k8s/sandbox/kustomization.yaml

resolves a few issues related CORS and the logo

feat: cors frontend issues

---

template/bootstrap-cluster/argocd.yaml

PR to add ArgoCD helm repo before trying to install it.

fix: add argocd helm repo

---

template/.github/workflows/main.yaml
template/.pre-commit-config.yaml

PR to fix github actions linting and pre-commit checks

fix(ci): github actions fail on old python and pre-commit versions

---

template/flake.nix

PR to bump nodejs version to 22

chore(flake): bump nodejs verion to 22
